name: TruffleHog Secrets Scan

on:
  push:
    branches: [main]

jobs:
  trufflehog-scan:
    name: Scan for Secrets with TruffleHog
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
      issues: write
    env:
      SCAN_PATH: "."

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y curl jq
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

      # - name: Run TruffleHog Scan (Filesystem)
      #   id: trufflehog
      #   run: |
      #     set +e
      #     trufflehog filesystem "$SCAN_PATH" \
      #       --results=verified,unknown \
      #       --fail \
      #       --json > trufflehog-output.json
      #     RESULT=$?
      #     cat trufflehog-output.json | jq
      #     echo "scan_result=$RESULT" >> "$GITHUB_OUTPUT"
      #     exit $RESULT

      # - name: Create GitHub Issue if Secrets Found
      #   if: failure()
      #   run: |
      #     echo "Creating GitHub issue due to detected secrets..."
      #     ISSUE_BODY=$(jq -r '.[] | "* File: \(.SourceMetadata.Data) \n  Reason: \(.Raw)' trufflehog-output.json)
      #     gh issue create \
      #       --title "Secrets Detected in Pull Request #${{ github.event.pull_request.number }}" \
      #       --body "TruffleHog found secrets:\n\n$ISSUE_BODY\n\nPlease rotate these credentials and remove them from the codebase." \
      #       --repo "${{ github.repository }}"
      # env:
      #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
