name: TruffleHog Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trufflehog-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download TruffleHog v3 binary
        run: |
          curl -sL https://github.com/trufflesecurity/trufflehog/releases/download/v3.68.2/trufflehog-linux-amd64 -o trufflehog
          chmod +x trufflehog
          sudo mv trufflehog /usr/local/bin/trufflehog

      - name: Verify TruffleHog installation
        run: |
          file /usr/local/bin/trufflehog
          trufflehog --version

      - name: Run TruffleHog scan
        run: |
          trufflehog filesystem --fail-verified
