name: TruffleHog Secret Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important: full history for diff scanning

      - name: Run TruffleHog OSS Action
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug --only-verified --json

      - name: Dump TruffleHog logs (for debugging)
        if: always()
        run: |
          echo "TruffleHog output:"
          echo "${{ steps.trufflehog.outputs.result || 'No result output' }}"

      - name: Fail if secrets found
        if: steps.trufflehog.outcome == 'failure'
        run: |
          echo "⚠️ TruffleHog found secrets or failed unexpectedly."
          exit 1
