name: TruffleHog Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and install TruffleHog v3 binary
        run: |
          curl -sL https://github.com/trufflesecurity/trufflehog/releases/download/v3.68.2/trufflehog_3.68.2_linux_amd64.tar.gz -o trufflehog.tar.gz
          tar -xzf trufflehog.tar.gz
          chmod +x trufflehog
          sudo mv trufflehog /usr/local/bin/trufflehog

      - name: Verify TruffleHog installation
        run: |
          file /usr/local/bin/trufflehog
          trufflehog --version

      - name: Run TruffleHog scan
        run: |
          trufflehog filesystem --fail-verified
