name: TruffleHog Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trufflehog-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download trufflehog CLI
        run: |
          curl -sL https://github.com/trufflesecurity/trufflehog/releases/latest/download/trufflehog-linux-amd64 -o trufflehog
          chmod +x trufflehog
          sudo mv trufflehog /usr/local/bin/trufflehog

      - name: Run truffleHog scan
        run: |
          trufflehog filesystem --fail
